### ISSUE TITLE
`Unexpectedly reusing a connection!` When Running Many Clients Simultaneously

### ISSUE THREAD

**Issue by TillMueller** [network-quality/goresponsiveness#47]
Hello,

I'm currently investigating the possiblity of using this measurement client to assess network performance when many clients are trying to access the network at the same time. The setup looks like this:
`[ clients ] -- [ WiFi AP with NAT ] -- [ server ]`

When running with 20 clients, most of them (about 15) do not finish the test successfully. Instead, they print `Unexpectedly reusing a connection!` and `A self probe sent using a new connection!`. I have attached the one client's and server's full `stdout` and `stderr` output below, both are running with `--debug`. The limit for most runs seems to be about five clients that run successfully.

I have not seen similar issues with other testing methodologies, leading me to believe that this is specific to this implementation. Please let me know if you need any additional information, thank you

Full client error:
```
A self probe sent using a new connection!
panic: false

goroutine 23 [running]:
github.com/network-quality/goresponsiveness/lgc.(*LoadGeneratingConnectionDownload).SetGotConnTimeInfo(0x49a8f4?, {0x6d36a0?, 0x73a360?, 0xa2d740?}, {{0x81cab8?, 0xc0000dc700?}, 0x60?, 0xa3?, 0xc00008f670?})
	/root/goresponsiveness/lgc/lgc.go:189 +0x1ca
github.com/network-quality/goresponsiveness/traceable.GenerateHttpTimingTracer.func6({{0x81cab8?, 0xc0000dc700?}, 0xe0?, 0xc5?, 0xc00008f6d0?})
	/root/goresponsiveness/traceable/traceable.go:59 +0x8b
golang.org/x/net/http2.traceGotConn(0xc000166030?, 0xc0000f0780, 0x1)
	/root/go/pkg/mod/golang.org/x/net@v0.7.0/http2/transport.go:3121 +0x1ee
golang.org/x/net/http2.(*Transport).RoundTripOpt(0xc0000ee3f0, 0xc0000f2100, {0x10?})
	/root/go/pkg/mod/golang.org/x/net@v0.7.0/http2/transport.go:560 +0x1ac
golang.org/x/net/http2.(*Transport).RoundTrip(0xc0000e83c0?, 0xc0000b6800?)
	/root/go/pkg/mod/golang.org/x/net@v0.7.0/http2/transport.go:513 +0x1b
net/http.(*Transport).roundTrip(0xc0000e83c0, 0xc0000f2100)
	/usr/local/go/src/net/http/transport.go:601 +0x7eb
net/http.(*Transport).RoundTrip(0x0?, 0x818b20?)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x19
net/http.send(0xc0000f2100, {0x818b20, 0xc0000e83c0}, {0x8?, 0x781520?, 0x0?})
	/usr/local/go/src/net/http/client.go:252 +0x5f7
net/http.(*Client).send(0xc0000a3830, 0xc0000f2100, {0x4eb2fe?, 0x6?, 0x0?})
	/usr/local/go/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc0000a3830, 0xc0000f2100)
	/usr/local/go/src/net/http/client.go:716 +0x8fb
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:582
github.com/network-quality/goresponsiveness/lgc.(*LoadGeneratingConnectionDownload).doDownload(0xc000280000, {0x81b280?, 0xc000094230})
	/root/goresponsiveness/lgc/lgc.go:379 +0x2fe
created by github.com/network-quality/goresponsiveness/lgc.(*LoadGeneratingConnectionDownload).Start
	/root/goresponsiveness/lgc/lgc.go:343 +0x315
```

Some general information about the setup:
Client OS / kernel:
```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
# uname -a
Linux [CLIENT] 4.15.0-208-generic #220-Ubuntu SMP Mon Mar 20 14:27:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Server OS / kernel:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
$ uname -a
Linux [SERVER] 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

I built the binaries in an Ubuntu Docker container and then copied them to the clients. They are orchestrated using Ansible, which starts the `responsiveness` clients in quick succession.

Client invocation:
`./networkQualityClient --config {{ server }} --rpmtimeout {{ run_timeout }} --prometheus-stats-filename {{ log_file }} --debug`

Server invocation:
`./networkQualityServer --config-name [SERVER] --cert-file cert.crt --key-file cert.key --listen-addr 10.200.120.10 --debug`

[client_stderr.log](https://github.com/network-quality/goresponsiveness/files/11303594/client_stderr.log)
[client_stdout.log](https://github.com/network-quality/goresponsiveness/files/11303595/client_stdout.log)
[server_stderr.log](https://github.com/network-quality/goresponsiveness/files/11303596/server_stderr.log)
[server_stdout.log](https://github.com/network-quality/goresponsiveness/files/11303598/server_stdout.log)

**Comment by hawkinsw** [comment]
Thank you for doing the testing! I really appreciate it! Just a quick question: Did you build with a version of the code later than https://github.com/network-quality/goresponsiveness/commit/d5ec3aba77624387711ffa90e6960e406e9790e6 

The fix that I published for the related issue was necessary but not sufficient. I believe that the fix in the above-referenced commit will *actually* fix the error. Sorry about the problems and I really, really appreciate you working with us!!

If you find anything else that I can fix, please let me know!

(PS: I use *I* to take responsibility for errors but *we* for any of the positive things that this code does -- *I* am the sole cause of errors!)

**Comment by TillMueller** [comment]
Hi,

Thanks a lot for the quick response! No need to apologize, I'm grateful for you taking the time to work on and maintain this implementation. Depending on where our research brings us I might also come back with other questions in the future.

I believe I built that client with https://github.com/network-quality/goresponsiveness/commit/b2e528e07842488e573aefe783f1da755f818ffa, but I'm not 100% sure. While the server prints the commit it was built from when invoked with `--version`, my client doesn't do that:
```
# ./networkQualityClient --version
goresponsiveness dev
```
but for now that's not a big issue (or maybe also already fixed!)

However, I just tried to build the client again (from https://github.com/network-quality/goresponsiveness/commit/e8358eb1133e00fc8eeb4fe54c220b8ad6a91564) and am now running into build errors (running in an `ubuntu:18.04` Docker container):
```
root@2237061bcc4a:~# go version
go version go1.20.3 linux/amd64
root@2237061bcc4a:~# git clone https://github.com/network-quality/goresponsiveness.git
Cloning into 'goresponsiveness'...
[...]
root@2237061bcc4a:~# cd goresponsiveness/
root@2237061bcc4a:~/goresponsiveness# go mod download
root@2237061bcc4a:~/goresponsiveness# go build networkQuality.go
networkQuality.go:35:2: no required module provides package github.com/network-quality/goresponsiveness/probe; to add it:
        go get github.com/network-quality/goresponsiveness/probe
root@2237061bcc4a:~/goresponsiveness# go get github.com/network-quality/goresponsiveness/probe
go: github.com/network-quality/goresponsiveness/probe: no matching versions for query "upgrade"
```

Using `make` has the same outcome, as does using `go` version `1.16.6` (the version mentioned in the [README](https://github.com/network-quality/goresponsiveness/blob/main/README.md)). I am also unable to build the image from the included [Dockerfile](https://github.com/network-quality/goresponsiveness/blob/main/Dockerfile) (same error)  - I hope I didn't just miss something. https://github.com/network-quality/goresponsiveness/commit/b2e528e07842488e573aefe783f1da755f818ffa meanwhile builds without issues.

Do you have any hints what might be going wrong here? The [link mentioned by `go build`](https://github.com/network-quality/goresponsiveness/probe) doesn't appear to exist.

**Comment by hawkinsw** [comment]
Thank you for mentioning this! It is important to fix -- it is an issue with the refactor that I recently did. Standby and I will fix!!

**Comment by hawkinsw** [comment]
Sorry for the problem -- I just pushed a new commit (9e9963f7767719e4c26e2345169d7768ec5151ac) that *should* fix the build error!

**Comment by TillMueller** [comment]
Build looks good - I'll run the test overnight and report back. Thanks!

**Comment by hawkinsw** [comment]
Great!! Sorry again for the build trouble!

**Comment by TillMueller** [comment]
Hello!

Unfortunately, the issue is not resolved completely. It now seems to take longer until the clients crash, but they still do, now with this message
```
(SelfDown Probe) Probe 8 at 2023-04-24 10:08:00.218000776 +0200 CEST m=+0.334065345 with info {0xc0002b8000 false false 0s} did not properly reuse a connection.
panic: true

goroutine 30 [running]:
github.com/network-quality/goresponsiveness/probe.Probe({0x81b5c0, 0xc000060230}, 0xc00019c530?, 0xc0000a81b0, {0xc00001e210, 0x25}, {0x0?, 0x0?}, 0x1, 0xc000186040, ...)
	/root/goresponsiveness/probe/probe.go:146 +0xa97
created by github.com/network-quality/goresponsiveness/rpm.CombinedProber.func1
	/root/goresponsiveness/rpm/rpm.go:161 +0x79c
```

or this one
```
(SelfUp Probe) Probe 4 at 2023-04-24 10:08:00.541849922 +0200 CEST m=+0.387210599 with info {0xc000114700 false false 0s} did not properly reuse a connection.
panic: true

goroutine 54 [running]:
github.com/network-quality/goresponsiveness/probe.Probe({0x81b5c0, 0xc0000601e0}, 0xc00019c5d0?, 0xc000184a80, {0xc0001aa0c0, 0x25}, {0x0?, 0x0?}, 0x0, 0xc000200000, ...)
	/root/goresponsiveness/probe/probe.go:146 +0xa97
created by github.com/network-quality/goresponsiveness/rpm.CombinedProber.func1
	/root/goresponsiveness/rpm/rpm.go:174 +0xf6"
```

Building commit https://github.com/network-quality/goresponsiveness/commit/9e9963f7767719e4c26e2345169d7768ec5151ac. If you need the server or `--debug` output please let me know.

Thank you!

**Comment by hawkinsw** [comment]
Sorry for the follow-up message. I have a hypothesis about why you see this
output, but I will need to see the `--debug` output. If you had that handy,
I would really, really appreciate seeing it!

Thanks again for your help!

I am *really* sorry that it doesn't work out of the box. It is exciting
that you are using the client and I hope that you are not deterred from use
by these errors.

Will

PS: It would be great (if you are interested) to have a Zoom/Teams so we
can hear about your research -- we would love to collaborate!!

**Comment by TillMueller** [comment]
> If you had that handy,
I would really, really appreciate seeing it!

Of course, no worries at all, here you go: 
[stdout.log](https://github.com/network-quality/goresponsiveness/files/11312501/stdout.log)
[stderr.log](https://github.com/network-quality/goresponsiveness/files/11312502/stderr.log)

These are from one of the clients that failed. Do you also need the server's log?

> I hope that you are not deterred from use
by these errors.

Certainly not, all good!

> PS: It would be great (if you are interested) to have a Zoom/Teams so we
can hear about your research -- we would love to collaborate!!

That sounds very compelling - I'm using the tool as part of my Master's thesis, so I'll talk to my supervisor and come back to you! 

Thanks!

**Comment by hawkinsw** [comment]
Hello @TillMueller -- *so* sorry for the delay (It's final-exam time for the students here in the States!). I have committed a change that *might* just solve the problem. Although the previous proposed fix closed the gap (in time) between when a load-generating connection is marked as `RUNNING` and the time that the probers are allowed to start using it, this patch should make it even tighter (and, I hope, airtight). I look forward to hearing what you have to say, but I completely understand that you are busy as well!

Good luck on your ongoing research and thank you for your patience!

Will

**Comment by TillMueller** [comment]
Hey Will,

No worries at all, if it's anything like here in Germany that is a very busy time for students and staff - so please don't stress about my bug reports too much.

I just tried with the client based on https://github.com/network-quality/goresponsiveness/commit/a0e0b1861d5b2d0d77e728042c915f5b7742e744, but I ran into issues again, this is the `stderr` output:

```
download: Load-generating connection with id 62 is in an unrecognizable state.
panic: download: Load-generating connection with id 62 is in an unrecognizable state.


goroutine 11 [running]:
github.com/network-quality/goresponsiveness/rpm.LoadGenerator.func1()
	/root/goresponsiveness/rpm/rpm.go:309 +0xee9
created by github.com/network-quality/goresponsiveness/rpm.LoadGenerator
	/root/goresponsiveness/rpm/rpm.go:238 +0x1e5
```

And here's `stdout`:
[stdout.log](https://github.com/network-quality/goresponsiveness/files/11331856/stdout.log)

I also want to stress that if there's anything you think might be wrong with my setup here, please let me know, just in case that's a possibility.

Thanks again very much for your help!

Till

**Comment by hawkinsw** [comment]
THIS IS FANTASTIC NEWS!! Looks like we have licked the one bug that you were seeing. I am going to pop this comment into a separate bug -- it is a known issue that I am still trying to determine how to handle. 

Does that sound okay to you?

Thanks again for your support! We really appreciate it!

**Comment by TillMueller** [comment]
> Looks like we have licked the one bug that you were seeing.

Awesome, thank you!
> Does that sound okay to you?

Of course - let me know if you need anything else from my side for debugging or testing.

Thank you,

Till

**Comment by hawkinsw** [comment]
> > Looks like we have licked the one bug that you were seeing.
> 
> Awesome, thank you!
> 
> > Does that sound okay to you?
> 
> Of course - let me know if you need anything else from my side for debugging or testing. Also, if this specific issue is resolved, feel free to close it.
> 

Fantastic! I will add you via `@` in the new issue!


> Thank you,
> 
> Till
